version: '3.4'

networks:
    network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.33.0.0/16

volumes:
  data: {}

services:
    dappmanager.dnp.dappnode.eth:
        build: ./build
        image: dappmanager.dnp.dappnode.eth:0.0.9
        container_name: DAppNodeCore-dappmanager.dnp.dappnode.eth
        restart: always
        volumes:
            - data:/usr/src/app/dnp_repo/
            - /usr/src/dappnode/DNCORE/:/usr/src/app/DNCORE/
            - /var/run/docker.sock:/var/run/docker.sock
        dns: 172.33.1.2
        networks:
            network:
                ipv4_address: 172.33.1.7